import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { createJiti } from "jiti";

// app/theme-presets.css is generated by scripts/generate-theme-css.mjs so a
// saved theme paints correctly before the runtime /api/themes fetch resolves.
// If it drifts from lib/theme.ts the first paint shows the wrong palette, so
// these tests compare the generated file against the runtime resolver.

const { resolveTheme, listThemeSets } = await createJiti(import.meta.url).import("./theme.ts");
const css = readFileSync(new URL("../app/theme-presets.css", import.meta.url), "utf8");

const PAINT_VARS = ["--bg", "--bg-panel", "--border", "--text", "--accent", "--user-bg", "--tool-bg"];

function blockFor(name, variant) {
  const selector = variant === "dark"
    ? `html.dark[data-theme="${name}"]`
    : `html:not(.dark)[data-theme="${name}"]`;
  const start = css.indexOf(selector);
  if (start < 0) return null;
  return css.slice(start, css.indexOf("}", start));
}

test("the generated stylesheet covers every built-in theme variant", () => {
  const themes = listThemeSets(undefined, true);
  assert.ok(themes.length > 0);
  for (const theme of themes) {
    if (theme.hasDark) assert.ok(blockFor(theme.name, "dark"), `missing dark block for ${theme.name}`);
    if (theme.hasLight) assert.ok(blockFor(theme.name, "light"), `missing light block for ${theme.name}`);
  }
});

test("generated variables match the runtime resolver for every theme variant", () => {
  const themes = listThemeSets(undefined, true);
  let checked = 0;
  for (const theme of themes) {
    for (const variant of ["dark", "light"]) {
      const resolved = resolveTheme(theme.name, variant);
      if (!resolved) continue;
      const block = blockFor(theme.name, variant);
      assert.ok(block, `missing ${variant} block for ${theme.name}`);
      for (const key of PAINT_VARS) {
        const expected = resolved.cssVars[key];
        if (expected === undefined) continue;
        const match = new RegExp(`${key}: ([^;]+);`).exec(block);
        assert.ok(match, `${theme.name}/${variant} missing ${key}`);
        assert.equal(match[1], expected, `${theme.name}/${variant} ${key} drifted from lib/theme.ts`);
        checked += 1;
      }
    }
  }
  assert.ok(checked > 100, `expected a meaningful number of comparisons, got ${checked}`);
});

test("the generated file is marked as generated so it is not hand-edited", () => {
  assert.match(css, /GENERATED by scripts\/generate-theme-css\.mjs/);
});

test("QT themes win name collisions in the generated stylesheet too", () => {
  // QT gruvbox dark background is #1d2021; the OpenChamber file differs.
  const block = blockFor("gruvbox", "dark");
  assert.match(block, /--bg: #1d2021;/);
});
